version: 0.0
os: linux

files:
  - source: build/libs/
    destination: /apps/agileboard/
  - source: agileboard.sh
    destination: /apps/agileboard/

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/prepare_app_installation.sh
      timeout: 300
      runas: root

  AfterInstall:
  - location: scripts/configure_app_service.sh
    timeout: 300
    runas: root

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
