version: 0.0
os: linux
files:
  - source: build/libs/agileboard-0.1.jar
    destination: /apps/agileboard/agileboard-0.1.jar
hooks:
  BeforeInstall:
    - location: scripts/setup_directory
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app
      timeout: 300
      runas: root
