spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agileboard?currentSchema=agileboard
    username: agileboard
    password: agileboard

  jpa:
      show-sql: true
      hibernate:
        ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: "*"
  shutdown:
    enabled: true
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8888